services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/frontend

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
