services:
  aels:
    build:
      context: .
      args:
        env: "dev"
    environment:
      POSTGRES_URL: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports: 
      - "5173:5173"
    volumes:
      - ./:/aels
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
