FROM node:alpine as svelte-build
WORKDIR /workspace
COPY frontend /workspace
RUN npm i
RUN npm run build

FROM golang:1.20.5-alpine as go-build
WORKDIR /workspace
COPY backend /workspace
RUN go build -o aels-server

FROM alpine:latest
WORKDIR /aels
COPY --from=svelte-build /workspace/build/ /aels/dist/
COPY --from=go-build /workspace/aels-server /aels/
COPY --from=go-build /workspace/aurelian.yml /aels/aurelian.yml
CMD [ "/aels/aels-server", "aurelian.yml" ]