services:
  aels:
    build:
      context: .
      args:
        env: "dev"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/postgres?schema=public"
      JWT_SECRET: "superdupersecretkey-couldneverbeguessedbyanyone"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      NODE_ENV: "dev"
    ports:
      - "5173:5173"
    volumes:
      - ./:/aels
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
