services:
  backend:
    build: ./backend
    ports:
      - "2140:2140"
    environment:
      PG_HOST: postgres
      PG_USER: postgres
      PG_PASS: postgres
      PG_PORT: "5432"
      PG_DB: postgres
      GO_ENV: dev
      JWT_SECRET: "SuperSecretKey"
      USER_CREATE_ACCESS_KEY: "givemeaccess!"
      TOGETHER_API_KEY: ${TOGETHER_API_KEY}
    volumes:
      - ./backend:/backend
      - go_modules:/go
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  go_modules:
