services:
  backend:
    build: ./backend
    environment:
      PG_HOST: postgres
      PG_USER: postgres
      PG_PASS: postgres
      PG_PORT: "5432"
      PG_DB: postgres
      JWT_SECRET: "SuperSecretKey"
      INFERENCE_BACKEND: http://inf
    volumes:
      - ./backend:/backend
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/frontend

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  inf:
    image: ghcr.io/huggingface/text-generation-inference:latest
    entrypoint: "text-generation-launcher --model-id MBZUAI/LaMini-Neo-125M"
    shm_size: "1gb"
    ports:
      - 4000:80
    volumes:
      - hf_data:/data

volumes:
  pg_data:
  hf_data:
