app = "aels-demo"
primary_region = "iad"

[build]
dockerfile = "Dockerfile.production"

[env]
PG_HOST = "ep-hidden-salad-10275909.us-east-2.aws.neon.tech"
PG_USER = "e253"
PG_PORT = "5432"
PG_DB = "neondb"

[http_service]
internal_port = 2140
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 2
processes = ["app"]

[http_service.concurrency]
type = "connections"
soft_limit = 200
hard_limit = 250

[http_services.checks]
path = "/health"
method = "GET"
grace_period = "2s"
interval = "30s"
timeout = "2s"
